global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

rule_files:

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090
    relabel_configs:
      - replacement: prometheus
        target_label: instance

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter-00:9100
          - node-exporter-01:9100
          - node-exporter-02:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:9100)?
        replacement: ${1}
        target_label: instance

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
